cmake_minimum_required(VERSION 3.18)
get_filename_component(lotus_root "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(selection_module "${lotus_root}/cmake/LotusOptions.cmake")

if(DEFINED FAILURE_CASE)
  set(LOTUS_BUILD_TESTS ON)
  set(LOTUS_ENABLE_CFL ON)
  set(LOTUS_TOOL_FAMILIES all CACHE STRING "")
  set(LOTUS_TEST_SUBSYSTEMS all CACHE STRING "")
  if(FAILURE_CASE STREQUAL "unknown-tool")
    set(LOTUS_TOOL_FAMILIES checkre)
  elseif(FAILURE_CASE STREQUAL "unknown-test")
    set(LOTUS_TEST_SUBSYSTEMS concurrncy)
  elseif(FAILURE_CASE STREQUAL "mixed-all")
    set(LOTUS_TOOL_FAMILIES "all;alias")
  elseif(FAILURE_CASE STREQUAL "disabled-cfl-tool")
    set(LOTUS_ENABLE_CFL OFF)
    set(LOTUS_TOOL_FAMILIES cfl)
  elseif(FAILURE_CASE STREQUAL "disabled-cfl-test")
    set(LOTUS_ENABLE_CFL OFF)
    set(LOTUS_TEST_SUBSYSTEMS cfl)
  elseif(FAILURE_CASE STREQUAL "unknown-group")
    set(LOTUS_TEST_SUBSYSTEMS concurrency/cudaa)
  endif()
  include("${selection_module}")
  return()
endif()

function(check_selection tools tests cfl expected_tools expected_tests)
  set(LOTUS_BUILD_TESTS ON)
  set(LOTUS_TOOL_FAMILIES "${tools}")
  set(LOTUS_TEST_SUBSYSTEMS "${tests}")
  set(LOTUS_ENABLE_CFL "${cfl}")
  include("${selection_module}")
  if(NOT "${LOTUS_SELECTED_TOOL_FAMILIES}" STREQUAL "${expected_tools}")
    message(FATAL_ERROR "Unexpected tool selection: ${LOTUS_SELECTED_TOOL_FAMILIES}")
  endif()
  if(NOT "${LOTUS_SELECTED_TEST_SUBSYSTEMS}" STREQUAL "${expected_tests}")
    message(FATAL_ERROR "Unexpected test selection: ${LOTUS_SELECTED_TEST_SUBSYSTEMS}")
  endif()
endfunction()

check_selection(all all ON
  "alias;checker;dataflow;optimization;solver;verifier;ir;cfl"
  "alias;alias-wrapper;analysis;checker;cfl;concurrency;dataflow;fuzzing;ir;solvers;symbolicexecution;utils;verification")
check_selection(all all OFF
  "alias;checker;dataflow;optimization;solver;verifier;ir"
  "alias;alias-wrapper;analysis;checker;concurrency;dataflow;fuzzing;ir;solvers;symbolicexecution;utils;verification")
check_selection("" "" ON "" "")
check_selection("Alias;IR;Alias" "Concurrency;alias-wrapper;Concurrency" OFF
  "alias;ir" "concurrency;alias-wrapper")
check_selection("" "Concurrency/CUDA;dataflow/vasco;analysis/cfg;alias/ptsset" OFF
  "" "concurrency/cuda;dataflow/vasco;analysis/cfg;alias/ptsset")

set(LOTUS_TEST_SUBSYSTEMS "concurrency/cuda;dataflow/vasco")
set(LOTUS_TOOL_FAMILIES "")
include("${selection_module}")
if(NOT "${LOTUS_SELECTED_TEST_ROOTS}" STREQUAL "concurrency;dataflow")
  message(FATAL_ERROR "Group selection did not select the correct parent directories")
endif()
lotus_test_group_enabled(concurrency cuda selected)
lotus_test_group_enabled(concurrency mpi omitted)
if(NOT selected OR omitted)
  message(FATAL_ERROR "Group selection did not restrict sibling groups")
endif()

foreach(failure unknown-tool unknown-test unknown-group mixed-all disabled-cfl-tool disabled-cfl-test)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DFAILURE_CASE=${failure}"
    -P "${CMAKE_CURRENT_LIST_FILE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(result EQUAL 0 OR NOT error MATCHES "(Unknown component|requires LOTUS_ENABLE_CFL)")
    message(FATAL_ERROR "${failure} did not produce the expected diagnostic: ${output}${error}")
  endif()
endforeach()
message(STATUS "Build selection checks passed")
