set(graph "${FIXTURES}/crossing.dot")
set(expected_status 0)
set(expected "query: may-reach")
set(args --query 0 4)
if(CASE STREQUAL "crossing_backward")
  list(APPEND args --direction pre)
elseif(CASE STREQUAL "mismatch")
  set(graph "${FIXTURES}/mismatch.dot")
  set(expected "query: unreachable")
elseif(CASE STREQUAL "spurious")
  set(graph "${FIXTURES}/spurious.dot")
  set(args --query 0 8)
elseif(CASE STREQUAL "call_prefix")
  set(graph "${FIXTURES}/prefix.dot")
  set(args --query 0 1 --call-prefix)
elseif(CASE STREQUAL "both_prefix")
  set(graph "${FIXTURES}/prefix.dot")
  set(args --query 0 2 --call-prefix --field-prefix)
elseif(CASE STREQUAL "pending_rejected")
  set(graph "${FIXTURES}/prefix.dot")
  set(args --query 0 1)
  set(expected "query: unreachable")
elseif(CASE STREQUAL "neutral")
  set(graph "${FIXTURES}/neutral.dot")
  set(args --query -9 3)
elseif(CASE STREQUAL "all_pairs")
  set(args --all-pairs --pairs)
  set(expected "candidate-pairs: 6")
elseif(CASE STREQUAL "batch")
  set(args --queries "${FIXTURES}/demands.txt" --pairs)
  set(expected "requested-pairs: 2.*candidate-pairs: 1.*pair: 0 4")
elseif(CASE STREQUAL "source")
  set(args --source 0 --pairs)
  set(expected "candidate-pairs: 2")
elseif(CASE STREQUAL "target")
  set(args --target 4 --pairs)
  set(expected "pair: 0 4")
elseif(CASE STREQUAL "isolated")
  set(graph "${FIXTURES}/empty.dot")
  set(args --vertex -123 --query -123 -123)
elseif(CASE STREQUAL "missing_vertex")
  set(args --query 99 4)
  set(expected_status 2)
  set(expected "query vertex is not in graph")
elseif(CASE STREQUAL "invalid_label")
  set(graph "${FIXTURES}/invalid.dot")
  set(args --all-pairs)
  set(expected_status 2)
  set(expected "invalid interleaved-Dyck label id")
elseif(CASE STREQUAL "bad_number")
  set(args --query 0garbage 4)
  set(expected_status 2)
  set(expected "invalid integer")
elseif(CASE STREQUAL "invalid_option")
  set(args --not-an-option)
  set(expected_status 2)
  set(expected "unknown option")
elseif(CASE STREQUAL "resource_limit")
  set(args --query 0 4 --max-transitions 1)
  set(expected_status 3)
  set(expected "no result returned")
elseif(CASE STREQUAL "help")
  set(args --help)
  set(expected "sound upper bound")
elseif(CASE STREQUAL "timings")
  list(APPEND args --timings)
  set(expected "setup-us: [0-9]+.*saturation-us: [0-9]+.*readout-us: [0-9]+")
elseif(CASE STREQUAL "missing_file")
  set(graph "${FIXTURES}/does-not-exist.dot")
  set(args --all-pairs)
  set(expected_status 2)
  set(expected "cannot open")
elseif(CASE STREQUAL "missing_scope")
  set(args)
  set(expected_status 2)
  set(expected "missing query scope")
elseif(CASE STREQUAL "invalid_backwards_prefix")
  set(args --query 0 4 --direction pre --call-prefix)
  set(expected_status 2)
  set(expected "prefix flags require a forward query")
elseif(NOT CASE STREQUAL "crossing_forward")
  message(FATAL_ERROR "Unknown CLI regression: ${CASE}")
endif()
execute_process(COMMAND "${PROGRAM}" spds ${args} "${graph}"
  RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT "${status}" STREQUAL "${expected_status}")
  message(FATAL_ERROR "${CASE}: expected exit ${expected_status}, got ${status}\n${out}\n${err}")
endif()
if(NOT "${out}${err}" MATCHES "${expected}")
  message(FATAL_ERROR "${CASE}: missing ${expected}\n${out}\n${err}")
endif()
if(NOT expected_status EQUAL 0 AND out MATCHES "query:|pair:|candidate-pairs:|engine:")
  message(FATAL_ERROR "${CASE}: failed operation emitted a result\n${out}")
endif()
