if(LOTUS_ENABLE_CLAM)
  add_subdirectory(clam)
endif()
if(LOTUS_ENABLE_SEAHORN)
  add_subdirectory(seahorn)
endif()
if(LOTUS_ENABLE_SMACK)
  add_subdirectory(smack)
endif()

add_subdirectory(SymAbsAI)
add_subdirectory(Sifa)
add_subdirectory(Backend)
# Currently, the frontend is only for Boolean program (bpl) and and parsed problem is only sent to lib/Dataflow/NPA. 
add_subdirectory(Frontend)
add_subdirectory(Transform)
add_subdirectory(Analysis)
