set(args --query 0 14 --observer "${FIXTURES}/correlation.observer")
set(graph "${FIXTURES}/correlation.dot")
set(expected 0)
set(pattern "query: unreachable.*reason: affine-separated")
if(CASE STREQUAL "correlation")
    list(APPEND args --certificate)
    set(pattern "certificate-verified-against-hulls: true")
elseif(CASE STREQUAL "automatic")
    set(args --query 0 14)
    set(pattern "query: unreachable")
elseif(CASE STREQUAL "identity")
    set(args --query 0 14 --identity)
    set(pattern "query: may-reach")
elseif(CASE STREQUAL "independent")
  list(APPEND args --mode independent)
  set(pattern "query: may-reach.*overlapping-independent-blocks")
elseif(CASE STREQUAL "backward")
  list(APPEND args --direction pre)
elseif(CASE STREQUAL "json")
    list(APPEND args --json --certificate)
    set(pattern "\"may_reach\":false.*\"reason\":\"affine-separated\".*\"verified_against_hulls\":true")
elseif(CASE STREQUAL "crossing")
    set(graph "${FIXTURES}/crossing.dot")
    set(args --query 0 4 --pairs)
    set(pattern "query: may-reach.*pair: 0 4")
elseif(CASE STREQUAL "mismatch")
    set(graph "${FIXTURES}/mismatch.dot")
    set(args --query 0 4)
    set(pattern "projection-rejected")
elseif(CASE STREQUAL "prefix")
    set(graph "${FIXTURES}/prefix.dot")
    set(args --query 0 2 --call-prefix --field-prefix)
    set(pattern "query: may-reach")
elseif(CASE STREQUAL "explicit")
    set(graph "${FIXTURES}/prefix.dot")
    set(args --query 0 2 --call-stack 5 --field-stack 9)
    set(pattern "query: may-reach")
elseif(CASE STREQUAL "source")
    set(args --source 0 --pairs)
    set(graph "${FIXTURES}/crossing.dot")
    set(pattern "pair: 0 4")
elseif(CASE STREQUAL "target")
    set(args --target 4 --pairs)
    set(graph "${FIXTURES}/crossing.dot")
    set(pattern "direction: pre\\*.*pair: 0 4")
elseif(CASE STREQUAL "allpairs")
    set(args --all-pairs --pairs --identity)
    set(graph "${FIXTURES}/crossing.dot")
    set(pattern "candidate-pairs: 6")
elseif(CASE STREQUAL "batch")
    set(args --queries "${FIXTURES}/demands.txt" --pairs --identity)
    set(graph "${FIXTURES}/crossing.dot")
    set(pattern "requested-pairs: 2.*candidate-pairs: 1.*pair: 0 4")
elseif(CASE STREQUAL "empty")
    set(args --all-pairs --json)
    set(graph "${FIXTURES}/empty.dot")
    set(pattern "\"candidate_pairs\":0")
elseif(CASE STREQUAL "isolated")
    set(args --query -9 -9 --vertex -9)
    set(graph "${FIXTURES}/empty.dot")
    set(pattern "query: may-reach")
elseif(CASE STREQUAL "observer_error")
    set(args --observer "${FIXTURES}/invalid.observer" --query 0 14)
    set(expected 2)
elseif(CASE STREQUAL "unknown")
    set(args --unknown)
    set(expected 2)
elseif(CASE STREQUAL "mode_error")
    set(args --all-pairs --mode exact)
    set(expected 2)
elseif(CASE STREQUAL "limit")
    list(APPEND args --max-updates 1)
    set(expected 3)
elseif(CASE STREQUAL "dimension_limit")
    list(APPEND args --max-dimension 2)
    set(expected 3)
elseif(CASE STREQUAL "automatic_dimension_limit")
    set(args --query 0 14 --max-dimension 2)
    set(expected 3)
elseif(CASE STREQUAL "missing_vertex")
    set(args --query 0 999)
    set(expected 2)
elseif(CASE STREQUAL "conflicting_options")
    list(APPEND args --identity)
    set(expected 2)
elseif(CASE STREQUAL "help")
    set(args --help)
    set(pattern "Usage:")
elseif(CASE STREQUAL "timings")
    list(APPEND args --timings)
    set(pattern "setup-us: [0-9]+.*saturation-us: [0-9]+.*readout-us: [0-9]+")
elseif(CASE STREQUAL "missing_scope")
    set(args)
    set(expected 2)
elseif(CASE STREQUAL "roundtrip")
    set(args --query 0 14 --dump-observer "${WORK}/affine-observer-roundtrip.txt")
    set(pattern "query: unreachable")
else()
    message(FATAL_ERROR "unknown CLI case ${CASE}")
endif()
execute_process(COMMAND "${PROGRAM}" affine-spds ${args} "${graph}"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT "${status}" STREQUAL "${expected}")
    message(FATAL_ERROR "${CASE}: exit ${status}, expected ${expected}\n${output}\n${error}")
endif()
if(expected EQUAL 0)
    if(NOT output MATCHES "${pattern}")
        message(FATAL_ERROR "${CASE}: missing ${pattern}\n${output}\n${error}")
    endif()
elseif(NOT output STREQUAL "")
    message(FATAL_ERROR "failure must not emit a partial result: ${output}")
endif()
if(CASE STREQUAL "roundtrip")
    execute_process(COMMAND "${PROGRAM}" affine-spds --query 0 14
        --observer "${WORK}/affine-observer-roundtrip.txt" "${graph}"
        RESULT_VARIABLE status2 OUTPUT_VARIABLE output2 ERROR_VARIABLE error2)
    file(REMOVE "${WORK}/affine-observer-roundtrip.txt")
    if(NOT status2 EQUAL 0 OR NOT output STREQUAL output2)
        message(FATAL_ERROR "observer round trip changed results\n${output2}\n${error2}")
    endif()
endif()
