#include "Concurrency/OpenMP/OpenMPOpKind.h"

namespace lotus::concurrency::OpenMP {

std::string openmpOpToString(OpenMPOpKind op) {
  switch (op) {
  case OpenMPOpKind::Task:
    return "TD_OMP_TASK";
  case OpenMPOpKind::TaskWait:
    return "TD_OMP_TASKWAIT";
  case OpenMPOpKind::TaskWaitDeps:
    return "TD_OMP_TASKWAIT_DEPS";
  case OpenMPOpKind::TaskYield:
    return "TD_OMP_TASKYIELD";
  case OpenMPOpKind::TaskgroupStart:
    return "TD_OMP_TASKGROUP_START";
  case OpenMPOpKind::TaskgroupEnd:
    return "TD_OMP_TASKGROUP_END";
  case OpenMPOpKind::TaskWithDeps:
    return "TD_OMP_TASK_WITH_DEPS";
  case OpenMPOpKind::Taskloop:
    return "TD_OMP_TASKLOOP";
  case OpenMPOpKind::TaskComplete:
    return "TD_OMP_TASK_COMPLETE";
  case OpenMPOpKind::SingleStart:
    return "TD_OMP_SINGLE_START";
  case OpenMPOpKind::SingleEnd:
    return "TD_OMP_SINGLE_END";
  case OpenMPOpKind::MasterStart:
    return "TD_OMP_MASTER_START";
  case OpenMPOpKind::MasterEnd:
    return "TD_OMP_MASTER_END";
  case OpenMPOpKind::OrderedStart:
    return "TD_OMP_ORDERED_START";
  case OpenMPOpKind::OrderedEnd:
    return "TD_OMP_ORDERED_END";
  case OpenMPOpKind::ReduceStart:
    return "TD_OMP_REDUCE_START";
  case OpenMPOpKind::ReduceEnd:
    return "TD_OMP_REDUCE_END";
  case OpenMPOpKind::ReduceNowaitStart:
    return "TD_OMP_REDUCE_NOWAIT_START";
  case OpenMPOpKind::ReduceNowaitEnd:
    return "TD_OMP_REDUCE_NOWAIT_END";
  case OpenMPOpKind::ForStaticInit:
    return "TD_OMP_FOR_STATIC_INIT";
  case OpenMPOpKind::ForStaticFini:
    return "TD_OMP_FOR_STATIC_FINI";
  case OpenMPOpKind::ForDispatchInit:
    return "TD_OMP_FOR_DISPATCH_INIT";
  case OpenMPOpKind::ForDispatchNext:
    return "TD_OMP_FOR_DISPATCH_NEXT";
  case OpenMPOpKind::ForDispatchFini:
    return "TD_OMP_FOR_DISPATCH_FINI";
  case OpenMPOpKind::SectionsInit:
    return "TD_OMP_SECTIONS_INIT";
  case OpenMPOpKind::SectionsNext:
    return "TD_OMP_SECTIONS_NEXT";
  case OpenMPOpKind::SectionsEnd:
    return "TD_OMP_SECTIONS_END";
  case OpenMPOpKind::AtomicStart:
    return "TD_OMP_ATOMIC_START";
  case OpenMPOpKind::AtomicEnd:
    return "TD_OMP_ATOMIC_END";
  case OpenMPOpKind::Flush:
    return "TD_OMP_FLUSH";
  case OpenMPOpKind::Cancel:
    return "TD_OMP_CANCEL";
  case OpenMPOpKind::CriticalStart:
    return "TD_OMP_CRITICAL_START";
  case OpenMPOpKind::CriticalEnd:
    return "TD_OMP_CRITICAL_END";
  case OpenMPOpKind::ParallelStart:
    return "TD_OMP_PARALLEL_START";
  case OpenMPOpKind::Target:
    return "TD_OMP_TARGET";
  case OpenMPOpKind::TargetDataBegin:
    return "TD_OMP_TARGET_DATA_BEGIN";
  case OpenMPOpKind::TargetDataEnd:
    return "TD_OMP_TARGET_DATA_END";
  case OpenMPOpKind::TargetDataUpdate:
    return "TD_OMP_TARGET_DATA_UPDATE";
  case OpenMPOpKind::Teams:
    return "TD_OMP_TEAMS";
  case OpenMPOpKind::TeamsHost:
    return "TD_OMP_TEAMS_HOST";
  case OpenMPOpKind::TeamsDistribute:
    return "TD_OMP_TEAMS_DISTRIBUTE";
  case OpenMPOpKind::Distribute:
    return "TD_OMP_DISTRIBUTE";
  case OpenMPOpKind::DistributeStatic:
    return "TD_OMP_DISTRIBUTE_STATIC";
  case OpenMPOpKind::DistributeDynamic:
    return "TD_OMP_DISTRIBUTE_DYNAMIC";
  case OpenMPOpKind::DistributeGuidance:
    return "TD_OMP_DISTRIBUTE_GUIDANCE";
  case OpenMPOpKind::LoopStaticInit:
    return "TD_OMP_LOOP_STATIC_INIT";
  case OpenMPOpKind::LoopDynamicInit:
    return "TD_OMP_LOOP_DYNAMIC_INIT";
  case OpenMPOpKind::LoopGuidanceInit:
    return "TD_OMP_LOOP_GUIDANCE_INIT";
  case OpenMPOpKind::Affinity:
    return "TD_OMP_AFFINITY";
  case OpenMPOpKind::ScopeStart:
    return "TD_OMP_SCOPE_START";
  case OpenMPOpKind::ScopeEnd:
    return "TD_OMP_SCOPE_END";
  case OpenMPOpKind::TaskloopSimd:
    return "TD_OMP_TASKLOOP_SIMD";
  case OpenMPOpKind::TaskloopFini:
    return "TD_OMP_TASKLOOP_FINI";
  case OpenMPOpKind::InteropInit:
    return "TD_OMP_INTEROP_INIT";
  case OpenMPOpKind::InteropFini:
    return "TD_OMP_INTEROP_FINI";
  case OpenMPOpKind::DoacrossInit:
    return "TD_OMP_DOACROSS_INIT";
  case OpenMPOpKind::DoacrossWait:
    return "TD_OMP_DOACROSS_WAIT";
  case OpenMPOpKind::DoacrossSubmit:
    return "TD_OMP_DOACROSS_SUBMIT";
  case OpenMPOpKind::Unknown:
    return "TD_OMP_UNKNOWN";
  }
  return "TD_OMP_UNKNOWN";
}

} // namespace lotus::concurrency::OpenMP