# Pointer Analysis Unit Tests

# Alias Analysis Tests
add_lotus_pointer_test(alloc_aa_test AllocAATest.cpp)
add_lotus_pointer_test(aser_pta_test AserPTATest.cpp)
add_lotus_pointer_test(dda_aa_test DDAATest.cpp)
add_lotus_pointer_test(dyck_aa_test DyckAATest.cpp)
add_lotus_pointer_test(sparrow_aa_test SparrowAATest.cpp)
add_lotus_pointer_test(tpa_test TPATest.cpp)
add_lotus_pointer_test(underapprox_aa_test UnderApproxAATest.cpp)
add_lotus_pointer_test(alias_graph_test AliasGraphTest.cpp)
add_lotus_pointer_test(dfpa_test DFPATest.cpp)
add_lotus_pointer_test(lotus_aa_test LotusAATest.cpp)
add_lotus_pointer_test(gvfg_lotus_adapter_test GVFGAdapterTest.cpp)
target_link_libraries(gvfg_lotus_adapter_test CanaryGuardedValueFlow)
