#include "Concurrency/MPI/MPISemanticOp.h"

#include "Concurrency/Utils/ThreadAPI.h"

namespace lotus::concurrency::mpi {

std::string mpiOpToString(MPIOpKind op) {
  switch (op) {
  case MPIOpKind::SessionInit:
    return "MPI_Session_init";
  case MPIOpKind::SessionFinalize:
    return "MPI_Session_finalize";
  case MPIOpKind::SessionGetInfo:
    return "MPI_Session_get_info";
  case MPIOpKind::SessionGetNumErrcodes:
    return "MPI_Session_get_num_errcodes";
  case MPIOpKind::SessionGetErrhandler:
    return "MPI_Session_get_errhandler";
  case MPIOpKind::SessionSetErrhandler:
    return "MPI_Session_set_errhandler";
  case MPIOpKind::ErrhandlerCreate:
    return "MPI_Errhandler_create";
  case MPIOpKind::ErrhandlerFree:
    return "MPI_Errhandler_free";
  case MPIOpKind::CommGetErrhandler:
    return "MPI_Comm_get_errhandler";
  case MPIOpKind::CommSetErrhandler:
    return "MPI_Comm_set_errhandler";
  case MPIOpKind::CommCallErrhandler:
    return "MPI_Comm_call_errhandler";
  case MPIOpKind::WinGetErrhandler:
    return "MPI_Win_get_errhandler";
  case MPIOpKind::WinSetErrhandler:
    return "MPI_Win_set_errhandler";
  case MPIOpKind::FileGetErrhandler:
    return "MPI_File_get_errhandler";
  case MPIOpKind::FileSetErrhandler:
    return "MPI_File_set_errhandler";
  case MPIOpKind::ErrorClass:
    return "MPI_Error_class";
  case MPIOpKind::ErrorString:
    return "MPI_Error_string";
  case MPIOpKind::InfoCreate:
    return "MPI_Info_create";
  case MPIOpKind::InfoDup:
    return "MPI_Info_dup";
  case MPIOpKind::InfoFree:
    return "MPI_Info_free";
  case MPIOpKind::InfoGet:
    return "MPI_Info_get";
  case MPIOpKind::InfoGetValuelen:
    return "MPI_Info_get_valuelen";
  case MPIOpKind::InfoGetNkeys:
    return "MPI_Info_get_nkeys";
  case MPIOpKind::InfoGetNthkey:
    return "MPI_Info_get_nthkey";
  case MPIOpKind::InfoGetKeyval:
    return "MPI_Info_get_keyval";
  case MPIOpKind::InfoSet:
    return "MPI_Info_set";
  case MPIOpKind::InfoDelete:
    return "MPI_Info_delete";
  case MPIOpKind::InfoC2F:
    return "MPI_Info_c2f";
  case MPIOpKind::InfoCreateEnv:
    return "MPI_Info_create_env";
  case MPIOpKind::InfoFreeEnv:
    return "MPI_Info_free_env";
  case MPIOpKind::GetCount:
    return "MPI_Get_count";
  case MPIOpKind::GetElements:
    return "MPI_Get_elements";
  case MPIOpKind::GetElementsX:
    return "MPI_Get_elements_x";
  case MPIOpKind::StatusSize:
    return "MPI_Status_size";
  case MPIOpKind::StatusSetElements:
    return "MPI_Status_set_elements";
  case MPIOpKind::StatusSetElementsX:
    return "MPI_Status_set_elements_x";
  case MPIOpKind::Mprobe:
    return "MPI_Mprobe";
  case MPIOpKind::Improbe:
    return "MPI_Improbe";
  case MPIOpKind::Imrecv:
    return "MPI_Imrecv";
  case MPIOpKind::Mrecv:
    return "MPI_Mrecv";
  case MPIOpKind::Init:
    return "MPI_Init";
  case MPIOpKind::Finalize:
    return "MPI_Finalize";
  case MPIOpKind::Send:
    return "MPI_Send";
  case MPIOpKind::Recv:
    return "MPI_Recv";
  case MPIOpKind::Sendrecv:
    return "MPI_Sendrecv";
  case MPIOpKind::Probe:
    return "MPI_Probe";
  case MPIOpKind::Isend:
    return "MPI_Isend";
  case MPIOpKind::Irecv:
    return "MPI_Irecv";
  case MPIOpKind::Iprobe:
    return "MPI_Iprobe";
  case MPIOpKind::PersistentSendInit:
    return "MPI_Send_init";
  case MPIOpKind::PersistentRecvInit:
    return "MPI_Recv_init";
  case MPIOpKind::RequestStart:
    return "MPI_Start";
  case MPIOpKind::Wait:
    return "MPI_Wait";
  case MPIOpKind::Waitall:
    return "MPI_Waitall";
  case MPIOpKind::Waitany:
    return "MPI_Waitany";
  case MPIOpKind::Waitsome:
    return "MPI_Waitsome";
  case MPIOpKind::Test:
    return "MPI_Test";
  case MPIOpKind::Testall:
    return "MPI_Testall";
  case MPIOpKind::Testany:
    return "MPI_Testany";
  case MPIOpKind::Testsome:
    return "MPI_Testsome";
  case MPIOpKind::Barrier:
    return "MPI_Barrier";
  case MPIOpKind::Bcast:
    return "MPI_Bcast";
  case MPIOpKind::Scatter:
    return "MPI_Scatter";
  case MPIOpKind::Gather:
    return "MPI_Gather";
  case MPIOpKind::Allgather:
    return "MPI_Allgather";
  case MPIOpKind::Alltoall:
    return "MPI_Alltoall";
  case MPIOpKind::Reduce:
    return "MPI_Reduce";
  case MPIOpKind::Allreduce:
    return "MPI_Allreduce";
  case MPIOpKind::ReduceScatter:
    return "MPI_Reduce_scatter";
  case MPIOpKind::Scan:
    return "MPI_Scan";
  case MPIOpKind::WinCreate:
    return "MPI_Win_create";
  case MPIOpKind::WinFree:
    return "MPI_Win_free";
  case MPIOpKind::Put:
    return "MPI_Put";
  case MPIOpKind::Get:
    return "MPI_Get";
  case MPIOpKind::Accumulate:
    return "MPI_Accumulate";
  case MPIOpKind::WinFence:
    return "MPI_Win_fence";
  case MPIOpKind::WinLock:
    return "MPI_Win_lock";
  case MPIOpKind::WinUnlock:
    return "MPI_Win_unlock";
  case MPIOpKind::WinFlush:
    return "MPI_Win_flush";
  case MPIOpKind::WinSync:
    return "MPI_Win_sync";
  case MPIOpKind::WinPost:
    return "MPI_Win_post";
  case MPIOpKind::WinStart:
    return "MPI_Win_start";
  case MPIOpKind::WinComplete:
    return "MPI_Win_complete";
  case MPIOpKind::WinWait:
    return "MPI_Win_wait";
  case MPIOpKind::WinTest:
    return "MPI_Win_test";
  case MPIOpKind::CommDup:
    return "MPI_Comm_dup";
  case MPIOpKind::CommSplit:
    return "MPI_Comm_split";
  case MPIOpKind::CommCreate:
    return "MPI_Comm_create";
  case MPIOpKind::CommFree:
    return "MPI_Comm_free";
  case MPIOpKind::RequestFree:
    return "MPI_Request_free";
  case MPIOpKind::Cancel:
    return "MPI_Cancel";
  case MPIOpKind::TypeContiguous:
    return "MPI_Type_contiguous";
  case MPIOpKind::TypeVector:
    return "MPI_Type_vector";
  case MPIOpKind::TypeHvector:
    return "MPI_Type_hvector";
  case MPIOpKind::TypeIndexed:
    return "MPI_Type_indexed";
  case MPIOpKind::TypeHindexed:
    return "MPI_Type_hindexed";
  case MPIOpKind::TypeStruct:
    return "MPI_Type_struct";
  case MPIOpKind::TypeCreateDlpack:
    return "MPI_Type_create_dlpack";
  case MPIOpKind::TypeCreateSubarray:
    return "MPI_Type_create_subarray";
  case MPIOpKind::TypeCreateDarray:
    return "MPI_Type_create_darray";
  case MPIOpKind::TypeCreateResized:
    return "MPI_Type_create_resized";
  case MPIOpKind::TypeCreateHindexed:
    return "MPI_Type_create_hindexed";
  case MPIOpKind::TypeCreateHvector:
    return "MPI_Type_create_hvector";
  case MPIOpKind::TypeGetExtent:
    return "MPI_Type_get_extent";
  case MPIOpKind::TypeGetTrueExtent:
    return "MPI_Type_get_true_extent";
  case MPIOpKind::TypeSize:
    return "MPI_Type_size";
  case MPIOpKind::TypeCommit:
    return "MPI_Type_commit";
  case MPIOpKind::CartCreate:
    return "MPI_Cart_create";
  case MPIOpKind::CartDimsCreate:
    return "MPI_Cart_dims_create";
  case MPIOpKind::CartGet:
    return "MPI_Cart_get";
  case MPIOpKind::CartShift:
    return "MPI_Cart_shift";
  case MPIOpKind::CartCoords:
    return "MPI_Cart_coords";
  case MPIOpKind::CartRank:
    return "MPI_Cart_rank";
  case MPIOpKind::CartSub:
    return "MPI_Cart_sub";
  case MPIOpKind::DistGraphCreate:
    return "MPI_Dist_graph_create";
  case MPIOpKind::DistGraphCreateAdjacent:
    return "MPI_Dist_graph_create_adjacent";
  case MPIOpKind::DistGraphNeighbors:
    return "MPI_Dist_graph_neighbors";
  case MPIOpKind::DistGraphNeighborsCount:
    return "MPI_Dist_graph_neighbors_count";
  case MPIOpKind::GraphCreate:
    return "MPI_Graph_create";
  case MPIOpKind::GraphGet:
    return "MPI_Graph_get";
  case MPIOpKind::GraphNeighbors:
    return "MPI_Graph_neighbors";
  case MPIOpKind::GraphNeighborsCount:
    return "MPI_Graph_neighbors_count";
  case MPIOpKind::GraphDimsGet:
    return "MPI_Graphdims_get";
  case MPIOpKind::GraphMap:
    return "MPI_Graph_map";
  case MPIOpKind::Unknown:
    return "MPI_Unknown";
  }
  return "MPI_Unknown";
}

MPIOpKind mpiOpFromTDType(int td_type) {
  switch (static_cast<ThreadAPI::TD_TYPE>(td_type)) {
  case ThreadAPI::TD_MPI_SESSION_INIT:
    return MPIOpKind::SessionInit;
  case ThreadAPI::TD_MPI_SESSION_FINALIZE:
    return MPIOpKind::SessionFinalize;
  case ThreadAPI::TD_MPI_SESSION_GET_INFO:
    return MPIOpKind::SessionGetInfo;
  case ThreadAPI::TD_MPI_SESSION_GET_NUM_ERRCODES:
    return MPIOpKind::SessionGetNumErrcodes;
  case ThreadAPI::TD_MPI_SESSION_GET_ERRHANDLER:
    return MPIOpKind::SessionGetErrhandler;
  case ThreadAPI::TD_MPI_SESSION_SET_ERRHANDLER:
    return MPIOpKind::SessionSetErrhandler;
  case ThreadAPI::TD_MPI_ERRHANDLER_CREATE:
    return MPIOpKind::ErrhandlerCreate;
  case ThreadAPI::TD_MPI_ERRHANDLER_FREE:
    return MPIOpKind::ErrhandlerFree;
  case ThreadAPI::TD_MPI_COMM_GET_ERRHANDLER:
    return MPIOpKind::CommGetErrhandler;
  case ThreadAPI::TD_MPI_COMM_SET_ERRHANDLER:
    return MPIOpKind::CommSetErrhandler;
  case ThreadAPI::TD_MPI_COMM_CALL_ERRHANDLER:
    return MPIOpKind::CommCallErrhandler;
  case ThreadAPI::TD_MPI_WIN_GET_ERRHANDLER:
    return MPIOpKind::WinGetErrhandler;
  case ThreadAPI::TD_MPI_WIN_SET_ERRHANDLER:
    return MPIOpKind::WinSetErrhandler;
  case ThreadAPI::TD_MPI_FILE_GET_ERRHANDLER:
    return MPIOpKind::FileGetErrhandler;
  case ThreadAPI::TD_MPI_FILE_SET_ERRHANDLER:
    return MPIOpKind::FileSetErrhandler;
  case ThreadAPI::TD_MPI_ERROR_CLASS:
    return MPIOpKind::ErrorClass;
  case ThreadAPI::TD_MPI_ERROR_STRING:
    return MPIOpKind::ErrorString;
  case ThreadAPI::TD_MPI_INFO_CREATE:
    return MPIOpKind::InfoCreate;
  case ThreadAPI::TD_MPI_INFO_DUP:
    return MPIOpKind::InfoDup;
  case ThreadAPI::TD_MPI_INFO_FREE:
    return MPIOpKind::InfoFree;
  case ThreadAPI::TD_MPI_INFO_GET:
    return MPIOpKind::InfoGet;
  case ThreadAPI::TD_MPI_INFO_GET_VALUELEN:
    return MPIOpKind::InfoGetValuelen;
  case ThreadAPI::TD_MPI_INFO_GET_NKEYS:
    return MPIOpKind::InfoGetNkeys;
  case ThreadAPI::TD_MPI_INFO_GET_NTHKEY:
    return MPIOpKind::InfoGetNthkey;
  case ThreadAPI::TD_MPI_INFO_GET_KEYVAL:
    return MPIOpKind::InfoGetKeyval;
  case ThreadAPI::TD_MPI_INFO_SET:
    return MPIOpKind::InfoSet;
  case ThreadAPI::TD_MPI_INFO_DELETE:
    return MPIOpKind::InfoDelete;
  case ThreadAPI::TD_MPI_INFO_C2F:
    return MPIOpKind::InfoC2F;
  case ThreadAPI::TD_MPI_INFO_CREATE_ENV:
    return MPIOpKind::InfoCreateEnv;
  case ThreadAPI::TD_MPI_INFO_FREE_ENV:
    return MPIOpKind::InfoFreeEnv;
  case ThreadAPI::TD_MPI_GET_COUNT:
    return MPIOpKind::GetCount;
  case ThreadAPI::TD_MPI_GET_ELEMENTS:
    return MPIOpKind::GetElements;
  case ThreadAPI::TD_MPI_GET_ELEMENTS_X:
    return MPIOpKind::GetElementsX;
  case ThreadAPI::TD_MPI_STATUS_SIZE:
    return MPIOpKind::StatusSize;
  case ThreadAPI::TD_MPI_STATUS_SET_ELEMENTS:
    return MPIOpKind::StatusSetElements;
  case ThreadAPI::TD_MPI_STATUS_SET_ELEMENTS_X:
    return MPIOpKind::StatusSetElementsX;
  case ThreadAPI::TD_MPI_MPROBE:
    return MPIOpKind::Mprobe;
  case ThreadAPI::TD_MPI_IMPROBE:
    return MPIOpKind::Improbe;
  case ThreadAPI::TD_MPI_IMRECV:
    return MPIOpKind::Imrecv;
  case ThreadAPI::TD_MPI_MRECV:
    return MPIOpKind::Mrecv;
  case ThreadAPI::TD_MPI_INIT:
    return MPIOpKind::Init;
  case ThreadAPI::TD_MPI_FINALIZE:
    return MPIOpKind::Finalize;
  case ThreadAPI::TD_MPI_SEND:
    return MPIOpKind::Send;
  case ThreadAPI::TD_MPI_RECV:
    return MPIOpKind::Recv;
  case ThreadAPI::TD_MPI_SENDRECV:
    return MPIOpKind::Sendrecv;
  case ThreadAPI::TD_MPI_PROBE:
    return MPIOpKind::Probe;
  case ThreadAPI::TD_MPI_ISEND:
    return MPIOpKind::Isend;
  case ThreadAPI::TD_MPI_IRECV:
    return MPIOpKind::Irecv;
  case ThreadAPI::TD_MPI_IPROBE:
    return MPIOpKind::Iprobe;
  case ThreadAPI::TD_MPI_PERSISTENT_SEND_INIT:
    return MPIOpKind::PersistentSendInit;
  case ThreadAPI::TD_MPI_PERSISTENT_RECV_INIT:
    return MPIOpKind::PersistentRecvInit;
  case ThreadAPI::TD_MPI_REQUEST_START:
    return MPIOpKind::RequestStart;
  case ThreadAPI::TD_MPI_WAIT:
    return MPIOpKind::Wait;
  case ThreadAPI::TD_MPI_WAITALL:
    return MPIOpKind::Waitall;
  case ThreadAPI::TD_MPI_WAITANY:
    return MPIOpKind::Waitany;
  case ThreadAPI::TD_MPI_WAITSOME:
    return MPIOpKind::Waitsome;
  case ThreadAPI::TD_MPI_TEST:
    return MPIOpKind::Test;
  case ThreadAPI::TD_MPI_TESTALL:
    return MPIOpKind::Testall;
  case ThreadAPI::TD_MPI_TESTANY:
    return MPIOpKind::Testany;
  case ThreadAPI::TD_MPI_TESTSOME:
    return MPIOpKind::Testsome;
  case ThreadAPI::TD_MPI_BARRIER:
    return MPIOpKind::Barrier;
  case ThreadAPI::TD_MPI_BCAST:
    return MPIOpKind::Bcast;
  case ThreadAPI::TD_MPI_SCATTER:
    return MPIOpKind::Scatter;
  case ThreadAPI::TD_MPI_GATHER:
    return MPIOpKind::Gather;
  case ThreadAPI::TD_MPI_ALLGATHER:
    return MPIOpKind::Allgather;
  case ThreadAPI::TD_MPI_ALLTOALL:
    return MPIOpKind::Alltoall;
  case ThreadAPI::TD_MPI_REDUCE:
    return MPIOpKind::Reduce;
  case ThreadAPI::TD_MPI_ALLREDUCE:
    return MPIOpKind::Allreduce;
  case ThreadAPI::TD_MPI_REDUCE_SCATTER:
    return MPIOpKind::ReduceScatter;
  case ThreadAPI::TD_MPI_SCAN:
    return MPIOpKind::Scan;
  case ThreadAPI::TD_MPI_WIN_CREATE:
    return MPIOpKind::WinCreate;
  case ThreadAPI::TD_MPI_WIN_FREE:
    return MPIOpKind::WinFree;
  case ThreadAPI::TD_MPI_PUT:
    return MPIOpKind::Put;
  case ThreadAPI::TD_MPI_GET:
    return MPIOpKind::Get;
  case ThreadAPI::TD_MPI_ACCUMULATE:
    return MPIOpKind::Accumulate;
  case ThreadAPI::TD_MPI_WIN_FENCE:
    return MPIOpKind::WinFence;
  case ThreadAPI::TD_MPI_WIN_LOCK:
    return MPIOpKind::WinLock;
  case ThreadAPI::TD_MPI_WIN_UNLOCK:
    return MPIOpKind::WinUnlock;
  case ThreadAPI::TD_MPI_WIN_FLUSH:
    return MPIOpKind::WinFlush;
  case ThreadAPI::TD_MPI_WIN_SYNC:
    return MPIOpKind::WinSync;
  case ThreadAPI::TD_MPI_WIN_POST:
    return MPIOpKind::WinPost;
  case ThreadAPI::TD_MPI_WIN_START:
    return MPIOpKind::WinStart;
  case ThreadAPI::TD_MPI_WIN_COMPLETE:
    return MPIOpKind::WinComplete;
  case ThreadAPI::TD_MPI_WIN_WAIT:
    return MPIOpKind::WinWait;
  case ThreadAPI::TD_MPI_WIN_TEST:
    return MPIOpKind::WinTest;
  case ThreadAPI::TD_MPI_COMM_DUP:
    return MPIOpKind::CommDup;
  case ThreadAPI::TD_MPI_COMM_SPLIT:
    return MPIOpKind::CommSplit;
  case ThreadAPI::TD_MPI_COMM_CREATE:
    return MPIOpKind::CommCreate;
  case ThreadAPI::TD_MPI_COMM_FREE:
    return MPIOpKind::CommFree;
  case ThreadAPI::TD_MPI_REQUEST_FREE:
    return MPIOpKind::RequestFree;
  case ThreadAPI::TD_MPI_CANCEL:
    return MPIOpKind::Cancel;
  case ThreadAPI::TD_MPI_TYPE_CONTIGUOUS:
    return MPIOpKind::TypeContiguous;
  case ThreadAPI::TD_MPI_TYPE_VECTOR:
    return MPIOpKind::TypeVector;
  case ThreadAPI::TD_MPI_TYPE_HVECTOR:
    return MPIOpKind::TypeHvector;
  case ThreadAPI::TD_MPI_TYPE_INDEXED:
    return MPIOpKind::TypeIndexed;
  case ThreadAPI::TD_MPI_TYPE_HINDEXED:
    return MPIOpKind::TypeHindexed;
  case ThreadAPI::TD_MPI_TYPE_STRUCT:
    return MPIOpKind::TypeStruct;
  case ThreadAPI::TD_MPI_TYPE_CREATE_DLPACK:
    return MPIOpKind::TypeCreateDlpack;
  case ThreadAPI::TD_MPI_TYPE_CREATE_SUBARRAY:
    return MPIOpKind::TypeCreateSubarray;
  case ThreadAPI::TD_MPI_TYPE_CREATE_DARRAY:
    return MPIOpKind::TypeCreateDarray;
  case ThreadAPI::TD_MPI_TYPE_CREATE_RESIZED:
    return MPIOpKind::TypeCreateResized;
  case ThreadAPI::TD_MPI_TYPE_CREATE_HINDEXED:
    return MPIOpKind::TypeCreateHindexed;
  case ThreadAPI::TD_MPI_TYPE_CREATE_HVECTOR:
    return MPIOpKind::TypeCreateHvector;
  case ThreadAPI::TD_MPI_TYPE_GET_EXTENT:
    return MPIOpKind::TypeGetExtent;
  case ThreadAPI::TD_MPI_TYPE_GET_TRUE_EXTENT:
    return MPIOpKind::TypeGetTrueExtent;
  case ThreadAPI::TD_MPI_TYPE_SIZE:
    return MPIOpKind::TypeSize;
  case ThreadAPI::TD_MPI_TYPE_COMMIT:
    return MPIOpKind::TypeCommit;
  case ThreadAPI::TD_MPI_CART_CREATE:
    return MPIOpKind::CartCreate;
  case ThreadAPI::TD_MPI_CART_DIMS_CREATE:
    return MPIOpKind::CartDimsCreate;
  case ThreadAPI::TD_MPI_CART_GET:
    return MPIOpKind::CartGet;
  case ThreadAPI::TD_MPI_CART_SHIFT:
    return MPIOpKind::CartShift;
  case ThreadAPI::TD_MPI_CART_COORDS:
    return MPIOpKind::CartCoords;
  case ThreadAPI::TD_MPI_CART_RANK:
    return MPIOpKind::CartRank;
  case ThreadAPI::TD_MPI_CART_SUB:
    return MPIOpKind::CartSub;
  case ThreadAPI::TD_MPI_DIST_GRAPH_CREATE:
    return MPIOpKind::DistGraphCreate;
  case ThreadAPI::TD_MPI_DIST_GRAPH_CREATE_ADJACENT:
    return MPIOpKind::DistGraphCreateAdjacent;
  case ThreadAPI::TD_MPI_DIST_GRAPH_NEIGHBORS:
    return MPIOpKind::DistGraphNeighbors;
  case ThreadAPI::TD_MPI_DIST_GRAPH_NEIGHBORS_COUNT:
    return MPIOpKind::DistGraphNeighborsCount;
  case ThreadAPI::TD_MPI_GRAPH_CREATE:
    return MPIOpKind::GraphCreate;
  case ThreadAPI::TD_MPI_GRAPH_GET:
    return MPIOpKind::GraphGet;
  case ThreadAPI::TD_MPI_GRAPH_NEIGHBORS:
    return MPIOpKind::GraphNeighbors;
  case ThreadAPI::TD_MPI_GRAPH_NEIGHBORS_COUNT:
    return MPIOpKind::GraphNeighborsCount;
  case ThreadAPI::TD_MPI_GRAPH_DIMS_GET:
    return MPIOpKind::GraphDimsGet;
  case ThreadAPI::TD_MPI_GRAPH_MAP:
    return MPIOpKind::GraphMap;
  default:
    return MPIOpKind::Unknown;
  }
}

} // namespace lotus::concurrency::mpi